In [1]:
import numpy as np

In [8]:
A = np.array([[0, 3, 2], [-3, 0, 1], [-2, -1, 0]])
print(np.allclose(A.T, -1 * A))
print(A.T)
print(-1*A)

True
[[ 0 -3 -2]
 [ 3  0 -1]
 [ 2  1  0]]
[[ 0 -3 -2]
 [ 3  0 -1]
 [ 2  1  0]]
